version: "3.9"

services:
   web:
      container_name: web
      image: vnikolaew/log-viewer.web:1.0.0
      pull_policy: always
      networks:
         default:
      environment:
         - NEXT_PUBLIC_API_URL=https://localhost:443/api
         - NEXT_PUBLIC_BASE_URL=https://localhost:443
      ports:
         - "3000:3000"
      depends_on:
         - server
      restart: on-failure
   server:
      image: vnikolaew/log-viewer.server:1.0.0
      pull_policy: always
      container_name: server
      environment:
         - ASPNETCORE_URLS=http://+:80;https://+:443
         - ASPNETCORE_ENVIRONMENT=Production
         - ASPNETCORE_Kestrel__Certificates__Default__Password=default
         - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      networks:
         default:
      volumes:
         - logs:/app/logs
         - ${USERPROFILE}/.aspnet/https:/https/
      expose:
         - "80"
         - "443"
      ports:
         - "80:80"
         - "443:443"
      restart: on-failure

volumes:
   logs:
networks:
   default:
